# Generated by ChatGPT. Prompt: "Convert this powershell script to bash. #build.ps1"
# Untested, as the developer is working on Windows.
scriptpath=$(readlink -f "$0")
dir=$(dirname "$scriptpath")
cd "$dir" || exit

docker swarm init --advertise-addr 127.0.0.1

docker-compose up --build

