version: '3.8'

services:
  web:
    build: .
    command: python seattlecontratunes/manage.py runserver 0.0.0.0:80
      
    ports:
      - 80:80
    env_file:
      - ./.env.dev
    depends_on:
      - db
    secrets:
      - DJANGO_SECRET_KEY

      
    
  db:
    image: postgres:15
    ports:
      - 5431:5431
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    


volumes:
  postgres_data:

secrets:
  DJANGO_SECRET_KEY:
    file: ./DJANGO_SECRET_KEY.txt
    #external: true
    #name: "${DJANGO_SECRET_KEY}"

  PORT:
    file: PORT.txt 

