# Generated by Django 5.0 on 2023-12-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("song_directory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medley",
            name="Tune2",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="medley",
            name="Tune3",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
