# Generated by Django 5.0 on 2023-12-20 19:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("song_directory", "0002_alter_medley_tune2_alter_medley_tune3"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentSection",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major", models.IntegerField(default=0)),
                ("minor", models.IntegerField(default=0)),
                ("patch", models.IntegerField(default=0)),
                ("details", models.TextField(default="")),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="song",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="song",
            name="uploaded_time",
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 12, 0)),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "content_posted",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="song_directory.commentsection",
                    ),
                ),
            ],
        ),
    ]
