# Generated by Django 5.0 on 2023-12-20 21:05

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("song_directory", "0004_alter_medley_id_alter_song_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medley",
            options={
                "permissions": [
                    ("can_delete_own_medley", "Can delete medleys uploaded by self")
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="song",
            options={
                "permissions": [
                    ("can_delete_own_song", "Can delete songs uploaded by self")
                ]
            },
        ),
        migrations.RenameField(
            model_name="medley",
            old_name="comments",
            new_name="notes",
        ),
        migrations.RemoveField(
            model_name="song",
            name="likes",
        ),
        migrations.AddField(
            model_name="medley",
            name="uploaded_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 12, 0)),
        ),
        migrations.AddField(
            model_name="medley",
            name="uploader_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medley",
            name="url_code",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="song",
            name="uploader_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="song",
            name="url_code",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="medley",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="uploaded_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 12, 0)),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="CommentSection",
        ),
    ]
