# Generated by Django 5.0 on 2023-12-20 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("song_directory", "0005_alter_medley_options_alter_song_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medley",
            old_name="uploader_id",
            new_name="uploader",
        ),
        migrations.RenameField(
            model_name="song",
            old_name="uploader_id",
            new_name="uploader",
        ),
    ]
