# Generated by Django 5.0 on 2023-12-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "song_directory",
            "0003_commentsection_version_song_likes_song_uploaded_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="medley",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="song",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
