# Generated by Django 5.0 on 2023-12-30 21:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("song_directory", "0007_medley_earliest_play_legacy_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="medley",
            name="uploaded_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 30, 21, 52, 34, 41768, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="uploaded_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 30, 21, 52, 34, 40627, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("url", models.CharField(max_length=128)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("Violence", "Violent or repulsive content"),
                            ("Hate", "Hateful or abusive content"),
                            ("Harassment", "Harassment or bullying"),
                            ("Harm", "Harmful or dangerous acts"),
                            ("Misinfo", "Misinformation"),
                            ("ChildAbuse", "Child abuse"),
                            ("Terrorism", "Promotes terrorism"),
                            ("Spam", "Spam or misleading"),
                            ("LegalIssue", "Legal issue"),
                            ("Other", "None of these are my issue"),
                        ],
                        max_length=128,
                    ),
                ),
                ("elaboration", models.CharField(max_length=4000)),
                ("email", models.EmailField(max_length=254)),
                (
                    "submitted_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            12,
                            30,
                            21,
                            52,
                            34,
                            40627,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
