# Generated by Django 5.0 on 2023-12-30 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "song_directory",
            "0008_alter_medley_uploaded_time_alter_song_uploaded_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="medley",
            name="uploaded_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 30, 22, 0, 11, 775795, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="submitted_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 30, 22, 0, 11, 774792, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="uploaded_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 30, 22, 0, 11, 775795, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
